### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by StephenMRicks85** [redmountainmakers/led_brick#1]
![snakedemo](https://cloud.githubusercontent.com/assets/13653153/9103375/499e32a0-3bc3-11e5-9c74-1bf6604ef0d4.gif)

**Comment by baird** [comment]
Just hosting the image this way? Ok to close? Thanks.

**Comment by nylen** [comment]
![rmm-led-matrix](https://cloud.githubusercontent.com/assets/227022/9108834/9342b7e0-3bf6-11e5-9786-397c2ee56e79.jpg)

**Comment by nylen** [comment]
![rmm-led-matrix-small](https://cloud.githubusercontent.com/assets/227022/9108882/de3a120c-3bf6-11e5-92d6-32fcf0478036.jpg)

**Comment by nylen** [comment]
![rmm-led-matrix-640](https://cloud.githubusercontent.com/assets/227022/9108911/241ec826-3bf7-11e5-8af0-ae5129cdbdfd.jpg)
